---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_args: '-o ControlMaster=no -o ControlPersist=no'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    update_required_webhook: "{{ lookup('env', 'ADW_UPDATE') }}"
    no_update_webhook: "{{ lookup('env', 'ADW_NOTIF') }}"
  tasks:
    - name: Check for updates
      apt:
        update_cache: yes
      register: apt_update_result

    - name: Get list of manually held packages
      shell: apt-mark showhold
      register: manually_held_packages
      changed_when: false

    - name: Get list of all upgradable packages
      shell: apt list --upgradable 2>/dev/null | grep -v '^Listing...' | cut -d'/' -f1
      register: all_upgradable_packages
      changed_when: false

    - name: Get list of packages that would be upgraded
      shell: apt-get --simulate dist-upgrade | grep '^Inst' | awk '{print $2}'
      register: would_be_upgraded
      changed_when: false

    - name: Identify system-held packages
      set_fact:
        system_held_packages: "{{ all_upgradable_packages.stdout_lines | difference(would_be_upgraded.stdout_lines) | difference(manually_held_packages.stdout_lines) }}"

    - name: Get details of upgradable packages
      shell: |
        apt list --upgradable 2>/dev/null | grep -v '^Listing...' | while read line; do
          pkg=$(echo $line | cut -d'/' -f1)
          if echo "{{ would_be_upgraded.stdout_lines | join(' ') }}" | grep -q "$pkg"; then
            echo "$line"
          fi
        done
      register: upgradable_packages_details
      changed_when: false

    - name: Count available updates
      set_fact:
        update_count: "{{ would_be_upgraded.stdout_lines | length }}"

    - name: Prepare Discord notification message
      set_fact:
        discord_message:
          embeds:
            - title: "🔄 Update Check for {{ inventory_hostname }}"
              color: "{{ '15158332' if update_count|int > 0 else '3066993' }}"  # Red if updates, Green if no updates
              fields:
                - name: "🖥️ Host"
                  value: "{{ inventory_hostname }}"
                  inline: true
                - name: "📦 Updates Available"
                  value: "{{ update_count }}"
                  inline: true
              description: |-
                {% if update_count|int > 0 %}
                **📋 Upgradable packages:**
                ```
                {% for package in upgradable_packages_details.stdout_lines %}
                • {{ package }}
                {% endfor %}
                ```
                {% else %}
                **✅ System is up to date!**
                {% endif %}
                {% if manually_held_packages.stdout_lines|length > 0 or system_held_packages|length > 0 %}
                **🔒 Held packages (excluded from update):**
                ```
                {% for package in manually_held_packages.stdout_lines %}
                • {{ package }} (manually held)
                {% endfor %}
                {% for package in system_held_packages %}
                • {{ package }} (system held)
                {% endfor %}
                ```
                {% else %}
                **🔓 No packages are being held back.**
                {% endif %}

    - name: Send Discord notification for updates required
      uri:
        url: "{{ update_required_webhook }}"
        method: POST
        body_format: json
        body: "{{ discord_message }}"
        status_code: [204, 200]  # Accept both 204 and 200 as success
      when: 
        - update_count|int > 0
        - update_required_webhook | length > 0

    - name: Send Discord notification for no updates required
      uri:
        url: "{{ no_update_webhook }}"
        method: POST
        body_format: json
        body: "{{ discord_message }}"
        status_code: [204, 200]  # Accept both 204 and 200 as success
      when: 
        - update_count|int == 0
        - no_update_webhook | length > 0

    - name: Display update check report (Debug)
      debug:
        var: discord_message
