---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_args: '-o ControlMaster=no -o ControlPersist=no'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    threshold_percent: 70
  tasks:
    - name: Create disk usage parser script
      ansible.builtin.copy:
        content: |
          #!/usr/bin/env python3
          import sys
          import json

          threshold = int(sys.argv[1])
          disks_over_threshold = []

          for line in sys.stdin:
              parts = line.strip().split()
              if len(parts) == 3:
                  device, usage, mount = parts
                  usage_percent = int(usage.rstrip('%'))
                  if usage_percent > threshold:
                      disks_over_threshold.append({
                          'device': device,
                          'usage': usage_percent,
                          'mount': mount
                      })

          print(json.dumps(disks_over_threshold))
        dest: /tmp/parse_disk_usage.py
        mode: '0755'

    - name: Get disk space usage and parse
      ansible.builtin.shell: df -h | awk '{if (NR!=1) {print $1,$5,$6}}' | grep -vE '^tmpfs|^udev|^/dev/loop' | python3 /tmp/parse_disk_usage.py {{ threshold_percent }}
      register: parsed_disk_usage
      changed_when: false

    - name: Set fact for disks over threshold
      ansible.builtin.set_fact:
        disks_over_threshold: "{{ parsed_disk_usage.stdout | from_json }}"

    - name: Prepare Discord notification message
      ansible.builtin.set_fact:
        discord_message:
          embeds:
            - title: "ðŸ’¾ Disk Space Alert for {{ inventory_hostname }}"
              color: 15158332  # Red color
              fields:
                - name: "ðŸ–¥ï¸ Host"
                  value: "{{ inventory_hostname }}"
                  inline: true
                - name: "ðŸš¨ Threshold"
                  value: "{{ threshold_percent }}%"
                  inline: true
                - name: "ðŸ”´ Disks Over Threshold"
                  value: "{{ disks_over_threshold | length }}"
                  inline: true
              description: |-
                The following disks are over {{ threshold_percent }}% usage:

                {% for disk in disks_over_threshold %}
                **ðŸ“€ Device:** `{{ disk.device }}`
                **ðŸ“Š Usage:** `{{ disk.usage }}%`
                **ðŸ“ Mount:** `{{ disk.mount }}`
                
                {% endfor %}
                
                Please check and free up space if necessary.
      when: disks_over_threshold | length > 0

    - name: Send Discord notification
      ansible.builtin.uri:
        url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"
        method: POST
        body_format: json
        body: "{{ discord_message }}"
        status_code: [204, 200]  # Accept both 204 and 200 as success
      when: 
        - disks_over_threshold | length > 0
        - lookup('env', 'DISCORD_WEBHOOK_URL') | length > 0

    - name: Debug disk usage (always show)
      ansible.builtin.debug:
        var: disks_over_threshold
