---
- hosts: grid_master
  gather_facts: no
  become: yes
  vars:
    ansible_remote_tmp: /tmp
    ansible_ssh_args: '-o ControlMaster=no -o ControlPersist=no'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    compose_dir: /home/ubuntu/dozzle

  tasks:
    - name: Check if docker-compose file exists
      stat:
        path: "{{ compose_dir }}/docker-compose.yml"
      register: compose_file

    - name: Fail if docker-compose.yml doesn't exist
      fail:
        msg: "docker-compose.yml not found in {{ compose_dir }}"
      when: not compose_file.stat.exists

    - name: Pull latest images
      community.docker.docker_compose:
        project_src: "{{ compose_dir }}"
        pull: yes
      register: pull_result

    - name: Check if any images were updated
      set_fact:
        images_updated: "{{ pull_result.changed }}"

    - name: Recreate containers with updated images
      community.docker.docker_compose:
        project_src: "{{ compose_dir }}"
        recreate: smart
        state: present
      when: images_updated

    - name: Prune unused images
      community.docker.docker_prune:
        images: yes
      when: images_updated
