---
- name: Redeploy Docker Compose Services - Dev
  hosts: ovh_master
  gather_facts: no
  become: yes
  vars:
    ansible_remote_tmp: /tmp
    ansible_ssh_args: "-o ControlMaster=auto -o ControlPersist=10m"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    manage_api_backend_dir: /home/debian/manage-api-backend/dev
    global_timeout: 600 # 10 minutes in seconds
  tasks:
    - name: Pull latest Docker images
      become: yes
      become_user: debian
      shell: cd {{ manage_api_backend_dir }} && docker compose pull
      register: docker_pull_result
      failed_when: docker_pull_result.rc != 0
      # Add timeout to prevent hanging
      async: "{{ global_timeout }}"
      poll: 5

    - name: Check if there are changes in Docker images
      set_fact:
        has_changes: "{{ 'Image is up to date' not in docker_pull_result.stdout }}"

    - name: Display no changes message
      debug:
        msg: "No changes detected in Docker images. Skipping restart."
      when: not has_changes

    - name: Change to manage-api-backend directory and stop Docker Compose services
      become: yes
      become_user: debian
      shell: cd {{ manage_api_backend_dir }} && docker compose down
      register: docker_down_result
      failed_when: docker_down_result.rc != 0
      # Add timeout to prevent hanging
      async: "{{ global_timeout }}"
      poll: 5
      when: has_changes

    - name: Start Docker Compose services with new images
      become: yes
      become_user: debian
      shell: cd {{ manage_api_backend_dir }} && docker compose up -d
      register: docker_up_result
      failed_when: docker_up_result.rc != 0
      # Add timeout to prevent hanging
      async: "{{ global_timeout }}"
      poll: 5
      when: has_changes

    - name: Check Docker Compose services status
      become: yes
      become_user: debian
      shell: cd {{ manage_api_backend_dir }} && docker compose ps
      register: docker_ps_result
      failed_when: docker_ps_result.rc != 0
      # Add timeout to prevent hanging
      async: 30
      poll: 5
      when: has_changes

    - name: Display Docker Compose services status
      debug:
        var: docker_ps_result.stdout_lines
      when: has_changes
