---
- name: Deploy Manage API Backend
  hosts: ovh_master
  gather_facts: no
  become: yes
  vars: 
    ansible_remote_tmp: /tmp
    ansible_ssh_args: '-o ControlMaster=auto -o ControlPersist=10m'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    manage_api_backend_dir: /home/debian/manage-api-backend
    global_timeout: 600  # 10 minutes in seconds
  tasks:
    - name: Change to manage-api-backend directory and docker compose restart
      become: yes
      become_user: debian
      shell: cd {{ manage_api_backend_dir }} && docker compose restart
      register: docker_result
      failed_when: docker_result.rc != 0
      changed_when: docker_result.stdout != 'Already up to date.'
      # Add timeout to prevent hanging
      async: "{{ global_timeout }}"
      poll: 5
 