---
- name: Update Coin List - Deni
  hosts: deni
  gather_facts: no
  become: no
  vars:
    ansible_remote_tmp: /tmp
    ansible_ssh_args: "-o ControlMaster=auto -o ControlPersist=10m"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    pb_config_ng_dir: /root/pb-config-ng-deni
    global_timeout: 600
  tasks:
    - name: Check if pb-config-ng directory exists
      stat:
        path: "{{ pb_config_ng_dir }}"
      register: dir_check

    - name: Fail if directory doesn't exist
      fail:
        msg: "Directory {{ pb_config_ng_dir }} does not exist"
      when: not dir_check.stat.exists

    - name: Check git repository status
      shell: cd {{ pb_config_ng_dir }} && git status --porcelain
      register: git_status
      changed_when: false
      failed_when: false

    - name: Change to pb-config-ng directory and pull latest changes
      shell: cd {{ pb_config_ng_dir }} && timeout 300 git pull
      register: git_result
      changed_when: git_result.stdout != 'Already up to date.'
      failed_when: git_result.rc != 0
      async: 360
      poll: 10

    - name: Display git pull result
      debug:
        msg: "Git pull output: {{ git_result.stdout }}"

    - name: Restart Docker Compose services if changes detected
      shell: cd {{ pb_config_ng_dir }} && timeout 300 ./docker_update.sh
      when: git_result.stdout != 'Already up to date.'
      register: docker_result
      failed_when: docker_result.rc != 0
      async: 360
      poll: 10

    - name: Display docker update result
      debug:
        msg: "Docker update output: {{ docker_result.stdout | default('No docker update needed') }}"

    - name: Display final status message
      debug:
        msg: "{{ 'Changes detected, services restarted' if git_result.stdout != 'Already up to date.' else 'No changes detected, no action taken' }}"
