---
- name: Proxmox Backup Integrity Check
  hosts: proxmox_node
  become: yes
  vars:
    proxmox_api_host: "localhost"
    proxmox_api_user: "root@pam"
    proxmox_api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
    discord_webhook: "{{ lookup('env', 'ADW_PB_CHECK') }}"
    backup_storage: "adata-dir"  # Change this if you use a different storage for backups

  tasks:
    - name: Get list of backups
      proxmox_backup_info:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        storage: "{{ backup_storage }}"
      register: backup_list

    - name: Verify backup integrity
      command: "vzdump verify {{ item.volid }}"
      loop: "{{ backup_list.proxmox_backups }}"
      register: verify_result
      ignore_errors: yes

    - name: Prepare backup integrity report
      set_fact:
        integrity_report:
          embeds:
            - title: "🔍 Proxmox Backup Integrity Report"
              color: 3066993
              fields:
                - name: "💾 Total Backups"
                  value: "{{ backup_list.proxmox_backups | length }}"
                  inline: true
                - name: "✅ Verified Backups"
                  value: "{{ verify_result.results | selectattr('rc', 'eq', 0) | list | length }}"
                  inline: true
                - name: "❌ Failed Verifications"
                  value: "{{ verify_result.results | selectattr('rc', 'ne', 0) | list | length }}"
                  inline: true
              description: |-
                **📊 Backup Integrity Details:**
                ```
                {% for result in verify_result.results %}
                • {{ result.item.vmid }} ({{ result.item.volid }}): {{ 'Passed' if result.rc == 0 else 'Failed' }}
                {% endfor %}
                ```
                {% if verify_result.results | selectattr('rc', 'ne', 0) | list | length > 0 %}
                **⚠️ Failed Verifications:**
                ```
                {% for result in verify_result.results | selectattr('rc', 'ne', 0) | list %}
                • {{ result.item.vmid }} ({{ result.item.volid }})
                  Error: {{ result.stderr_lines | join(' ') }}
                {% endfor %}
                ```
                {% endif %}

    - name: Send Discord notification
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body: "{{ integrity_report }}"
        status_code: [204, 200]
      when: discord_webhook | length > 0

    - name: Display integrity report (Debug)
      debug:
        var: integrity_report
