---
- name: Proxmox Performance Monitoring
  hosts: proxmox_node
  become: yes
  vars:
    ansible_ssh_args: '-o ControlMaster=no -o ControlPersist=no'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    discord_webhook: "{{ lookup('env', 'ADW_PROXMOX') }}"
    cpu_threshold: 10
    memory_threshold: 10
    storage_threshold: 10

  tasks:
    - name: Collect system-wide performance metrics
      shell: |
        echo "CPU Usage: $(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\\([0-9.]*\\)%* id.*/\\1/" | awk '{print 100 - $1}')%"
        echo "Memory Usage: $(free | grep Mem | awk '{print $3/$2 * 100.0}')%"
        echo "Storage Usage: $(df -h / | awk '/\// {print $5}')"
      register: system_metrics

    - name: Collect VM metrics
      shell: |
        echo "Virtual Machines:"
        qm list | tail -n +2 | while read vm; do
          vmid=$(echo $vm | awk '{print $1}')
          name=$(echo $vm | awk '{print $2}')
          status=$(echo $vm | awk '{print $3}')
          if [ "$status" = "running" ]; then
            if [ -f "/var/run/qemu-server/${vmid}.pid" ]; then
              pid=$(cat "/var/run/qemu-server/${vmid}.pid")
              vm_stats=$(top -b -n1 -p $pid | tail -n 1)
              cpu=$(echo $vm_stats | awk '{print $9}')
              mem=$(echo $vm_stats | awk '{print $10}')
              printf "• %s (ID: %s) CPU: %.1f%%, Mem: %.1f%%\n" "$name" "$vmid" $cpu $mem
            else
              echo "• $name (ID: $vmid) - PID file not found"
            fi
          fi
        done
      register: vm_metrics

    - name: Collect LXC metrics
      shell: |
        echo "LXC Containers:"
        pct list | tail -n +2 | while read ct; do
          ctid=$(echo $ct | awk '{print $1}')
          name=$(echo $ct | awk '{print $3}')
          status=$(echo $ct | awk '{print $2}')
          if [ "$status" = "running" ]; then
            cpu=$(pct exec $ctid -- top -bn1 | grep "Cpu(s)" | sed "s/.*, *\\([0-9.]*\\)%* id.*/\\1/" | awk '{print 100 - $1}')
            mem=$(pct exec $ctid -- free | grep Mem | awk '{print $3/$2 * 100.0}')
            printf "• %s (ID: %s) CPU: %.1f%%, Mem: %.1f%%\n" "$name" "$ctid" $cpu $mem
          fi
        done
      register: lxc_metrics

    - name: Generate performance report
      set_fact:
        performance_report: |
          {
            "embeds": [
              {
                "title": "Proxmox Performance Report",
                "color": 16711680,
                "fields": [
                  {
                    "name": "System Metrics",
                    "value": "**CPU Usage**: {{ system_metrics.stdout_lines[0].split(': ')[1] }}\n**Memory Usage**: {{ system_metrics.stdout_lines[1].split(': ')[1] }}\n**Storage Usage**: {{ system_metrics.stdout_lines[2].split(': ')[1] }}"
                  },
                  {
                    "name": "Virtual Machines",
                    "value": "{{ vm_metrics.stdout }}"
                  },
                  {
                    "name": "LXC Containers",
                    "value": "{{ lxc_metrics.stdout }}"
                  }
                ]
              }
            ]
          }

    - name: Send Discord notification with embed
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body: "{{ performance_report }}"
        status_code: [204, 200]
      when: discord_webhook | length > 0
