---
- name: Proxmox Log Analysis
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_remote_tmp: /tmp
    ansible_ssh_args: '-o ControlMaster=auto -o ControlPersist=10m'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    discord_webhook: "{{ lookup('env', 'ADW_PROXMOX') }}"
    log_paths:
      - "/var/log/syslog"
      - "/var/log/auth.log"
      - "/var/log/pve-firewall.log"
    error_patterns:
      - "error"
      - "failed"
      - "critical"
    security_patterns:
      - "authentication failure"
      - "Failed password"
      - "Invalid user"
    global_timeout: 600  # 10 minutes in seconds

  pre_tasks:
    - name: Include pre-requisite tasks
      include_tasks: _prereq_tasks.yml

  tasks:
    - name: Collect and analyze logs
      shell: |
        for log in {{ log_paths | join(' ') }}; do
          echo "Analyzing $log:"
          echo "  Errors found:"
          grep -iE "{{ error_patterns | join('|') }}" $log | tail -n 5
          echo "  Security incidents:"
          grep -iE "{{ security_patterns | join('|') }}" $log | tail -n 5
        done
      register: log_analysis
      async: "{{ global_timeout }}"
      poll: 5

    - name: Generate log analysis report
      set_fact:
        log_report:
          embeds:
            - title: "📜 Proxmox Log Analysis Report"
              color: 15158332  # Red color for potential issues
              fields:
                - name: "🔍 Log Analysis Results"
                  value: "{{ log_analysis.stdout }}"
              description: |-
                Summary of recent log entries:
                - Total errors: {{ log_analysis.stdout | regex_findall(error_patterns | join('|')) | length }}
                - Security incidents: {{ log_analysis.stdout | regex_findall(security_patterns | join('|')) | length }}

                Please review the detailed log entries for more information.
              footer:
                text: "Report generated on {{ ansible_date_time.iso8601 }}"

    - name: Send Discord notification
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body: "{{ log_report }}"
        status_code: [204, 200]
      when: discord_webhook | length > 0
      async: "{{ global_timeout }}"
      poll: 5

    - name: Display log analysis report (Debug)
      debug:
        var: log_report
