---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_args: '-o ControlMaster=no -o ControlPersist=no'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      register: apt_update_result

    - name: Get upgradable packages (dry-run)
      command: apt-get -s upgrade
      register: upgrade_dry_run
      changed_when: false

    - name: Parse upgradable packages
      set_fact:
        upgradable_packages: "{{ upgrade_dry_run.stdout_lines | select('match', '^Inst.*') | list }}"

    - name: Get list of held packages
      shell: apt-mark showhold
      register: held_packages
      changed_when: false

    - name: Perform apt upgrade
      apt:
        upgrade: yes
      register: apt_upgrade_result
      when: upgradable_packages | length > 0

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Set notification flag
      set_fact:
        should_notify: "{{ (upgradable_packages | length > 0) or reboot_required_file.stat.exists }}"

    - name: Prepare Discord notification message
      set_fact:
        discord_message:
          embeds:
            - title: "🔄 Apt Upgrade Report for {{ inventory_hostname }}"
              color: "{{ '15158332' if reboot_required_file.stat.exists else '3066993' }}"
              fields:
                - name: "🖥️ Host"
                  value: "{{ inventory_hostname }}"
                  inline: true
                - name: "📦 Upgraded Packages"
                  value: "{{ upgradable_packages | length }}"
                  inline: true
              description: |-
                {% if reboot_required_file.stat.exists %}
                **⚠️ REBOOT REQUIRED ⚠️**
                A system restart is necessary to complete the upgrade process.
                {% endif %}

                {% if upgradable_packages | length > 0 %}
                **📋 Upgraded Packages:**
                ```
                {% for package in upgradable_packages %}
                • {{ package | regex_replace('^Inst\\s+(\\S+).*$', '\\1') }}
                {% endfor %}
                ```
                {% else %}
                **📋 No packages were upgraded in this run.**
                {% endif %}

                {% if held_packages.stdout_lines | length > 0 %}
                **🔒 Held Packages:**
                ```
                {% for package in held_packages.stdout_lines %}
                • {{ package }}
                {% endfor %}
                ```
                {% else %}
                **🔓 No packages are being held back.**
                {% endif %}
      when: should_notify

    - name: Send Discord notification
      uri:
        url: "{{ lookup('env', 'ADW_UPDATE') }}"
        method: POST
        body_format: json
        body: "{{ discord_message }}"
        status_code: [204, 200]  # Accept both 204 and 200 as success
      when: should_notify and lookup('env', 'ADW_UPDATE') | length > 0

    - name: Display upgrade report (Debug)
      debug:
        var: discord_message
      when: should_notify
